## https://www.appveyor.com/docs/appveyor-yml/
image: Ubuntu2004
version: 1.0.{build}

platform: Any CPU

pull_requests:  
  do_not_increment_build_number: true

environment:
  BUILDKIT_PROGRESS: plain
  DOCKER_USER: corts
  DOCKER_PASS:
    secure: 0rxw6OrmXRqB3UuBZFbC/w==

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: Get-ChildItem "Env:"
- ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
- docker version

build_script:
- ps: >-
    $buildNumber = $env:APPVEYOR_BUILD_NUMBER;
    $branch = $env:APPVEYOR_REPO_BRANCH;
    .\build.ps1 -buildCounter $buildNumber -pushImage;
    docker images;
