#!/bin/sh
## start nginx (kept getting errors in supervisord that port was in use, restarts?)
#nginx -g "daemon off;"
/usr/sbin/nginx -c /etc/nginx/nginx.conf
## start start supervisor to manage all of the processes
/usr/bin/supervisord
