[supervisord]
nodaemon=true
logfile=/var/log/supervisord/supervisord.log    ; supervisord log file
logfile_maxbytes=50MB                           ; maximum size of logfile before rotation
logfile_backups=10                              ; number of backed up logfiles
loglevel=info                                   ; info, debug, warn, trace
childlogdir=/var/log/supervisord/               ; where child log files will live
user=root
pidfile=/run/supervisord.pid


[program:webapi]
directory=/app/PolicyServer/
command=dotnet PolicyServer.dll

#[program:nginx]
#command=/usr/sbin/nginx
#stdout_events_enabled=true
#stderr_events_enabled=true

#[program:nginx]
#command=nginx -c /etc/nginx/nginx.conf


[program:nginx]
command=nginx -g 'daemon off;'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
startretries=0
