[supervisord]
nodaemon=true
logfile=/var/log/supervisord/supervisord.log    ; supervisord log file
logfile_maxbytes=50MB                           ; maximum size of logfile before rotation
logfile_backups=10                              ; number of backed up logfiles
loglevel=info                                   ; info, debug, warn, trace
childlogdir=/var/log/supervisord/               ; where child log files will live

[program:webapi]
directory=/app/PolicyServer/
command=dotnet PolicyServer.dll

#[program:nginx]
#command=/usr/sbin/nginx
#stdout_events_enabled=true
#stderr_events_enabled=true

